### ISSUE TITLE
Problem with displayName

### ISSUE THREAD

**Issue by karolfalkiewicz** [Igorbek/typescript-plugin-styled-components#24] opened 2018-11-20 08:26 UTC
I added this plugin to my webpack configuration with is using `ts-loader`. Done everything according with README. Plugin works fine, but got issue with configuring the `displayName` in react dev tools. Currently it always display components name as `styled.h1`, `styled.p` etc.. I would like to see actual variable names here like the Babel version of plugin does it as default. So for example instead `styled.h1` i would like to see `Title`.  Another thing is way to customize the classNames added to component. Currently it is always the - `sc-xxxxx` or something similar with hash. Babel plugin has option to insert here also the displayName of component. As result it will end up with `Title` in React dev tools and in classNames. I hope this is understandable.

**Comment by karolfalkiewicz** [comment] 2018-11-20 08:43
Ok it is possible to fix 1st part by manually setting the displayName for component, but this isn't very pleasant. Would prefer way to do it automatically.

**Comment by Igorbek** [comment] 2018-11-20 16:32
Sorry to hear this. Can you please create a repository that reproduces the issue.
- include your webpack configuration
- example typescript code that uses styled-components
- describe how you build and run it

Please see how other reporter created a repo that reproduced his issue: https://github.com/Igorbek/typescript-plugin-styled-components/issues/13#issuecomment-404464576 ( [repo](https://github.com/Ky6uk/tpsc-tagged-templates-bug))

**Comment by Igorbek** [comment] 2019-02-18 21:21
I'm closing it since no more feedback.
@karolfalkiewicz please feel free to bring more info once you have.

**Closed by Igorbek** 2019-02-18 21:21 UTC
Labels: needs more info

**Comment by brianHolonis** [comment] 2019-04-13 00:00
Is is possible to automatically assign a display name to styled-components or is it necessary to use .withConfig to set the displayName? I'm using typescript. How could I configure it to allow for automatic displayName assignment? Thanks

**Comment by Igorbek** [comment] 2019-04-13 00:04
@brianHolonis This issue is closed. I moved your question to a new issue #42
